const allProducts = [
    {
        id: `OTN100`,
        name: `Cargo Box Small`,
        image: `add-image-url-here`,
        description: `Small sized cargo boxes are ideal for moving, storing or shipping your smaller household items.`,
        price: 1.99,
        quantity: 200,
        available: { online: true, store: true },
        shipping: { free: false, standard: true},
        category: `Box`,
        size: `Small`,
        weight: 0.5
    },{
        id: `OTN101`,
        name: `Cargo Box Medium`,
        image: `add-image-url-here`,
        description: `Medium sized cargo boxes are ideal for moving, storing or shipping your medium household items.`,
        price: 2.99,
        quantity: 150,
        available: { online: true, store: true },
        shipping: { free: false, standard: true},
        category: `Box`,
        size: `Medium`,
        weight: 0.7
    },{
        id: `OTN102`,
        name: `Cargo Box Large`,
        image: `add-image-url-here`,
        description: `Large sized cargo boxes are ideal for moving, storing or shipping your larger household items.`,
        price: 3.99,
        quantity: 125,
        available: { online: true, store: true },
        shipping: { free: false, standard: true},
        category: `Box`,
        size: `Large`,
        weight: 0.8
    },{
        id: `OTN103`,
        name: `Cargo Box Extra Large`,
        image: `add-image-url-here`,
        description: `Extra large sized cargo boxes are ideal for moving, storing or shipping your extra larger household items.`,
        price: 4.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: false, standard: true},
        category: `Box`,
        size: `Extra Large`,
        weight: 0.9
    },{
        id: `OTN104`,
        name: `Packaging Paper Tape Small`,
        image: `add-image-url-here`,
        description: `Packaging Paper Tape is ideal for moving and storage. It easily tears by hand and is self-sticking.`,
        price: 2.99,
        quantity: 200,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `27 Metre`,
        weight: 0.2
    },{
        id: `OTN105`,
        name: `Packaging Paper Tape Medium`,
        image: `add-image-url-here`,
        description: `Packaging Paper Tape is ideal for moving and storage. It easily tears by hand and is self-sticking.`,
        price: 3.99,
        quantity: 150,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `40 Metre`,
        weight: 0.3
    },{
        id: `OTN106`,
        name: `Packaging Paper Tape Large`,
        image: `add-image-url-here`,
        description: `Packaging Paper Tape is ideal for moving and storage. It easily tears by hand and is self-sticking.`,
        price: 4.99,
        quantity: 120,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `60 Metre`,
        weight: 0.4
    },{
        id: `OTN107`,
        name: `Packaging Paper Tape Extra Large`,
        image: `add-image-url-here`,
        description: `Packaging Paper Tape is ideal for moving and storage. It easily tears by hand and is self-sticking.`,
        price: 5.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `100 Metre`,
        weight: 0.5
    },{
        id: `OTN108`,
        name: `Duct Tape Small`,
        image: `add-image-url-here`,
        description: `A moisture resistance tape with easy tear and conformability.`,
        price: 10.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `100 Metre`,
        weight: 0.5
    },{
        id: `OTN109`,
        name: `Duct Tape Large`,
        image: `add-image-url-here`,
        description: `A moisture resistance tape with easy tear and conformability.`,
        price: 18.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `200 Metre`,
        weight: 1
    },{
        id: `OTN110`,
        name: `Electrical Tape Small`,
        image: `add-image-url-here`,
        description: `High temperature conformable elastic thick tape.`,
        price: 14.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `200 Metre`,
        weight: 0.5
    },{
        id: `OTN111`,
        name: `Electrical Tape Large`,
        image: `add-image-url-here`,
        description: `High temperature conformable elastic thick tape.`,
        price: 19.99,
        quantity: 100,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `150 Metre`,
        weight: 0.7
    },{
        id: `OTN112`,
        name: `White Tape`,
        image: `add-image-url-here`,
        description: `Great for assembling moving and cargo boxes. No blades or knives required.`,
        price: 9.99,
        quantity: 50,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Tape`,
        size: `100 Metre`,
        weight: 0.4
    },{
        id: `OTN113`,
        name: `Luggage Box`,
        image: `add-image-url-here`,
        description: `Box handle makes it easy to use as a suitcase for travel or for shipping.`,
        price: 6.99,
        quantity: 50,
        available: { online: false, store: true },
        shipping: { free: false, standard: true},
        category: `Box`,
        size: `Large`,
        weight: 0.7
    },{
        id: `OTN114`,
        name: `Matress Bag Twin`,
        image: `add-image-url-here`,
        description: `Matress bags will keep your mattresses or box springs protected against dust, soil, and light.`,
        price: 4.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Bag`,
        size: `Twin`,
        weight: 0.7
    },{
        id: `OTN115`,
        name: `Matress Bag Queen`,
        image: `add-image-url-here`,
        description: `Matress bags will keep your mattresses or box springs protected against dust, soil, and light.`,
        price: 5.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Bag`,
        size: `Queen`,
        weight: 0.7
    },{
        id: `OTN116`,
        name: `Matress Bag King`,
        image: `add-image-url-here`,
        description: `Matress bags will keep your mattresses or box springs protected against dust, soil, and light.`,
        price: 6.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Bag`,
        size: `King`,
        weight: 0.8
    },{
        id: `OTN117`,
        name: `Sofa Cover`,
        image: `add-image-url-here`,
        description: `Sofa Cover is great for protecting sofas, couches and other furniture from debris`,
        price: 7.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Cover`,
        size: `Large`,
        weight: 0.3
    },{
        id: `OTN117`,
        name: `Chair Cover`,
        image: `add-image-url-here`,
        description: `Chair Cover is great for protecting chairs, stools and other furniture from debris`,
        price: 7.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Cover`,
        size: `Medium`,
        weight: 0.3
    },{
        id: `OTN118`,
        name: `Bubble Wrap Small`,
        image: `add-image-url-here`,
        description: `Bubble wrap is efficient way to protect and wrap fragile items such as glassware, electronics, artwork, home decor and more.`,
        price: 17.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Wrap`,
        size: `Small`,
        weight: 0.5
    },{
        id: `OTN119`,
        name: `Bubble Wrap Medium`,
        image: `add-image-url-here`,
        description: `Bubble wrap is efficient way to protect and wrap fragile items such as glassware, electronics, artwork, home decor and more.`,
        price: 29.99,
        quantity: 75,
        available: { online: true, store: true },
        shipping: { free: true, standard: false},
        category: `Wrap`,
        size: `Medium`,
        weight: 0.9
    },{
        id: `OTN120`,
        name: `Bubble Wrap Large`,
        image: `add-image-url-here`,
        description: `Bubble wrap is efficient way to protect and wrap fragile items such as glassware, electronics, artwork, home decor and more.`,
        price: 35.99,
        quantity: 75,
        available: { online: false, store: true },
        shipping: { free: false, standard: true},
        category: `Wrap`,
        size: `Large`,
        weight: 0.9
    },
];